# Generated by Django 3.1.5 on 2021-02-16 10:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=240)),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(upload_to='blogb/avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=240)),
                ('short_title', models.CharField(max_length=240)),
                ('site_name', models.CharField(default=None, max_length=240)),
                ('slogan', models.CharField(max_length=240)),
                ('logo', models.ImageField(upload_to='blogb/logo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='TechNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(max_length=240)),
                ('tech_description', models.CharField(max_length=300)),
                ('tech_progress', models.IntegerField(default=0)),
                ('tech_img', models.ImageField(default='Img 351x100px', upload_to='blogb/tech_img')),
                ('tech_url', models.URLField(default='Url to doc site', max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('title_short', models.CharField(default='Krótki opis dla fancy odnosnikow obrazkowych', max_length=340)),
                ('content_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('photo_text', models.ImageField(default='pic_01.jpg', upload_to='blogb/img_text')),
                ('category', models.ManyToManyField(default=1, to='blogb.Category')),
            ],
        ),
    ]
