# Generated by Django 3.1.5 on 2021-02-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_name',
        ),
        migrations.AddField(
            model_name='author',
            name='author_firstname',
            field=models.CharField(default='Firstname', max_length=240),
        ),
        migrations.AddField(
            model_name='author',
            name='author_surname',
            field=models.CharField(default='Surname', max_length=240),
        ),
    ]
